drop table t_user if exists;
create table t_user (user_id int generated by default as identity, user_name varchar(20) not null, primary key (user_id));

drop table t_project if exists;
create table t_project (prj_id int generated by default as identity, prj_name varchar(50) not null, primary key (prj_id));

drop table t_user_detail if exists;
create table t_user_detail (user_id int, gender char(1) not null default 'X', addr varchar(200) null, primary key (user_id));

drop table t_projects if exists;
create table t_projects (prj_id int not null, user_id int not null);